import type { Metadata, Viewport } from 'next';
import { Chakra_Petch, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import './styles/ok.module.scss';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});
const chakra = Chakra_Petch({
    variable: '--font-chakra',
    weight: ['400', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'UNK — Edition',
    description: 'Generated by create next app',
    icons: { icon: '/icon.ico' },
};

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${chakra.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
